### ISSUE TITLE
Hoppers / Pipes can pull out of the fuel slot

### ISSUE THREAD

**Issue by brisingraerowing** [MasterGeneral156/Enderfuge#1]
This doesn't happen with the vanilla furnace (or any other modded machine with a fuel slot [that I tried]). Could that be changed? I would like to automate this with hoppers, but I can't due to this.

**Comment by MasterGeneral156** [comment]
Of course! I'll take a look and see what's up!

**Comment by MasterGeneral156** [comment]
1.1.9 should fix this for you! Thanks for reporting it!
